name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build_stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test_stage: 
    runs-on: ubuntu-latest
    needs: build_stage
    steps:
      - name: Check uptime
        run: uptime -p
      - name: cpu info and memory in megabytes
        run: |
          lscpu
          nproc
          free -m
      - name: kernel information
        run: uname -r
      
